[package]
name = "dioxus-canvas"
version = "0.2.2"
authors = ["@dementhos"]
edition = "2021"
description = "Canvas wrapper for Dioxus"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react", "canvas"]
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-core = { path = "../core", version = "^0.2.1" }
dioxus-core-macro = { path = "../core-macro", version = "^0.2.0" }
dioxus-html = { path = "../html", version = "^0.2.1" }
dioxus-hooks = { path = "../hooks", version = "^0.2.1" }
piet = "0.5.0"
piet-web = "0.5.0"
tokio = { version = "1.19.2", features = ["time"] }
web-sys = { version = "0.3", features = ["CanvasRenderingContext2d", "HtmlCanvasElement"] }
wasm-bindgen = "0.2"

log = "0.4.6"
wasm-logger = "0.2.0"
