[package]
name = "axum-streaming"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { workspace = true }
dioxus-fullstack = { workspace = true }
serde = "1.0.159"
simple_logger = "4.2.0"
tracing-wasm = "0.2.1"
tracing.workspace = true
tracing-subscriber = "0.3.17"
futures = "0.3.30"
kalosm-llama = { version = "0.1", optional = true }
tokio = { workspace = true, optional = true }
futures-util.workspace = true
tokio-stream = { version = "0.1.14", optional = true }
once_cell = "1.19.0"

[features]
default = []
ssr = ["dioxus-fullstack/axum", "kalosm-llama", "tokio", "tokio-stream"]
web = ["dioxus-fullstack/web"]
