[package]
name = "const-serialize"
version = "0.6.0-alpha.5"
edition = "2021"

[dependencies]
const-serialize-macro = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
const-serialize = { path = "." }
rand.workspace = true

[features]
test-big-endian = []
serde = ["dep:serde"]
