[package]
name = "const-serialize"
version = "0.6.0-alpha.4"
edition = "2021"

[dependencies]
const-serialize-macro = { workspace = true }

[dev-dependencies]
const-serialize = { path = "." }

[features]
test-big-endian = []
