[package]
name = "dioxus-interpreter-js"
version = "0.2.1"
edition = "2018"
authors = ["Jonathan Kelley"]
description = "JS Intepreter for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://docs.rs/dioxus"
keywords = ["dom", "ui", "gui", "react", "wasm"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = { version = "0.2.79" }
js-sys = { version = "0.3.56" }
web-sys = { version = "0.3.56", features = ["Element", "Node"] }
# sledgehammer-bindgen = { path = "d:/users/desktop/github/sledgehammer-bindgen" }
sledgehammer-bindgen = { git = "https://github.com/Demonthos/sledgehammer-bindgen" }
ux = "0.1.5"
dioxus-core = { path = "../core" }
dioxus-html = { path = "../html" }

[features]
default = []
web = []